# bbrx config.yml test

deadzones:
  ly: 32
  lx: 32
  ry: 32
  rx: 32
  brake: 64
  throttle: 64

beefzones:
  ly: 500
  lx: 500
  ry: 500
  rx: 500
  brake: 1000
  throttle: 1000

bindings:
# servo channel 1
- action: BB_ACTION_SERVO
  event: BB_EVENT_ANALOG_LY
  min: -512
  max: 511
  pin: 12

# servo channel 2
- action: BB_ACTION_SERVO
  event: BB_EVENT_ANALOG_LX
  min: 511
  max: -512
  pin: 13

# weapon control
- action: BB_ACTION_SERVO
  event: BB_EVENT_ANALOG_BRAKE
  min: -1024
  max: 1023
  pin: 14

- action: BB_ACTION_SERVO
  event: BB_EVENT_ANALOG_THROTTLE
  min: 1023
  max: -1024
  pin: 14

# speed control
- action: BB_ACTION_SPEED_UP
  event: BB_EVENT_BTN_B
  min: 0
  max: 1

- action: BB_ACTION_SPEED_UP
  event: BB_EVENT_DPAD_UP
  min: 0
  max: 1

- action: BB_ACTION_SPEED_DOWN
  event: BB_EVENT_BTN_X
  min: 0
  max: 1

- action: BB_ACTION_SPEED_DOWN
  event: BB_EVENT_DPAD_DOWN
  min: 0
  max: 1

# break
- action: BB_ACTION_BRAKE
  event: BB_EVENT_BTN_A
  min: 0
  max: 1

# gpio test
- action: BB_ACTION_GPIO
  event: BB_EVENT_BTN_B
  min: 0
  max: 1
  pin: 25
